### ISSUE TITLE
[FEATURE] ho i can use it to download videos of tiktok? not single example

### ISSUE THREAD

**Issue by estatistics** [hansputera/tiktok-dl#101]
[FEATURE] ho i can use it to download videos of tiktok? not single example

yarn install OK
then? what?

tiktok_download what?

**Comment by hansputera** [comment]
> [FEATURE] ho i can use it to download videos of tiktok? not single example
> 
> yarn install OK
> then? what?
> 
> tiktok_download what? 

This project is Rest API project.To use the API, may you read https://docs.tdl.besecure.eu.org/

**Comment by hansputera** [comment]
Feel free to reply this comment, or create new issue if you have any questions
