### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ThisMe124** [hansputera/tiktok-dl#11]
Apakah Bisa Di Buatkan Versi Npm/Package? :(

**Comment by hansputera** [comment]
> Apakah Bisa Di Buatkan Versi Npm/Package? :(

Ide bagus.

Namun saat ini untuk [tiktok-dl](https://github.com/hansputera/tiktok-dl.git) saya fokuskan terlebih dahulu untuk menjadi Rest API yang dimana mempermudah utk di _consume_ yang bisa dipergunakan di mana saja.

Di project ini juga kita masih menggunakan perantara. Jadi, sewaktu waktu perantara tersebut bisa mengubah caranya mereka agar data mereka tidak di _scrape/diambil_.

Kebetulan juga, saya lagi cari cara mudah untuk download videonya tanpa menggunakan perantara sehingga kita tidak perlu khawatir juga kalau salah satu perantaranya _down/mengubah caranya mereka_
