### ISSUE TITLE
[BUG] - dltik

### ISSUE THREAD

**Issue by flolep2607** [hansputera/tiktok-dl#13]
**Describe the bug**

**To Reproduce**
https://tiktok-dl.tslab.site/api/download?type=dltik&url=https://www.tiktok.com/@__crina/video/7026294925805292802

**Expected behavior**
get the video

**Screenshots**
{"error":"Cannot read property 'dynamicCover' of undefined"}

**Query Params (please complete the following information):**
 - URL: [[e.g. https://www.tiktok.com/@raphaeltangg/video/7027045794377190658]](https://tiktok-dl.tslab.site/api/download?type=dltik&url=https://www.tiktok.com/@__crina/video/7026294925805292802)
 - Type dltik (Provider)

**Comment by flolep2607** [comment]
there is also an error in the wiki:
https://github.com/hansputera/tiktok-dl/wiki/Endpoints#download 
Downloader source platform (tikmate, snaptik, ttdownloader, ttsave, dltik, savefrom, musicalydown, dddtik, firetik, savetik, lovetik, downtik, tikdown, tokup)
=> 
snaptik, tikmate, musicalydown, ttdownloader, ttsave, dltik, savefrom, savetik, tikdown, downtik, lovetik, dddtik, tokup, ttdownloaderone

**Comment by rizkyoye** [comment]
@flolep2607 P

**Comment by hansputera** [comment]
Hello @flolep2607 

Thanks for the report, I will immediately fix the DLTIK provider and check the other provider is still working or not.

**Comment by hansputera** [comment]
Sorry, I don't think I can fix it quickly. And, I mark DLTik as maintenance 🙏
But, now the wiki page has moved to https://docs.tiktok-dl.tslab.site 😃

**Comment by flolep2607** [comment]
ah ok thx
