### ISSUE TITLE
[BUG] - Run Dev  ERROR  yarn.lock: could not unmarshal lockfile: yaml: line 9: mapping values are not allowed in this context error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### ISSUE THREAD

**Issue by dinanlefasar** [hansputera/tiktok-dl#19]

**Comment by hansputera** [comment]
Hello, thanks for the report. Which yarn-pkg version do you use?

**Comment by dinanlefasar** [comment]
iam using
yarn version 1.22.17
Mac OS monterey

install depedency all fine, but after Run Dev error like this
Run Dev ERROR yarn.lock: could not unmarshal lockfile: yaml: line 9: mapping values are not allowed in this context error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

and i try deploy in https://vercel.com/, iam got same problem

**Comment by hansputera** [comment]
Hi, thanks for the information :smile: 

1. Maybe you can try to upgrade your yarn-pkg version to the berry version (see https://yarnpkg.com/getting-started/migration)
2. If you're trying to deploy in Vercel, set the root directory to "apps/web", see the photos below.

![rootdir photo](https://user-images.githubusercontent.com/47862061/158004276-88339ed2-d4dc-473b-81cc-8ce4206097ca.png)
![build and development settings](https://user-images.githubusercontent.com/47862061/158004297-52897296-4015-4b48-8c89-47f5168d7661.png)
