### ISSUE TITLE
New Provider List

### ISSUE THREAD

**Issue by hansputera** [hansputera/tiktok-dl#6]
TODO:

- [x] Add savetik.net
- ~~Add [inflact.com](https://inflact.com/downloader/tiktok/)~~ (reCaptcha issue like #5)
- [x] Add firetik.com
- [x] Add tikdown.org
- [x] Add downtik.net
- [x] Add lovetik.com
- [x] Add dddtik.com

**Comment by ridhwan-aziz** [comment]
@hansputera isu

**Comment by takedowndmca** [comment]
dddtik.com
