### ISSUE TITLE
Provider parameter not working

### ISSUE THREAD

**Issue by frozenpandaman** [hansputera/tiktok-dl#77]
The docs at https://docs.tdl.besecure.eu.org/getting-started/how-to-use say that the URL params should specify the key `type`, with the provider strings listed [here](https://docs.tdl.besecure.eu.org/additional/provider), but that doesn't seem to work, e.g. `https://tdl.besecure.eu.org/api/download?type=snaptik&url=...` gives URLs from a different provider than the one specified. Could you help? Thanks!

**Comment by hansputera** [comment]
Hello, can you give me the URL of the video, and the API response?

**Comment by frozenpandaman** [comment]
I seem to be temporarily blocked, so I can't figure out which video it was until I'm able to access the service again. Have been getting a mix of `{"message":"Please try again, you are getting ratelimit!"}` and a blank page with the title of `500: Internal Server Error` for over an hour now :( Sorry for the trouble!

**Comment by frozenpandaman** [comment]
@hansputera This is still going on – it seems my IP is blocked, so I can't investigate further. Can you help?

**Comment by hansputera** [comment]
Hello, sorry for the inconvenience, I have updated the production deployment to https://github.com/hansputera/tiktok-dl/commit/e4b9a415a634eb17eca7a5893a1192739045e2ea, can you try it again?

**Comment by frozenpandaman** [comment]
@hansputera Still getting the error, e.g.

https://tdl.besecure.eu.org/api/download?url=https://www.tiktok.com/@sfbart/video/7116980310327282987

Shows either
```
{"message":"Please try again, you are getting ratelimit!"}
```
or a blank white page with the `<title>` of `500: Internal Server Error`

**Comment by hansputera** [comment]
Can you try again? I just updated the production deployment to https://github.com/hansputera/tiktok-dl/pull/17/commits/c5534833d64fef46c23a2c1cacc2762c2f9a4cfd

**Comment by frozenpandaman** [comment]
@hansputera Awesome! Everything seems to be working perfectly now, including the `provider` parameter in my first post :) Thanks a ton!
