### ISSUE TITLE
Feature missing on Snaptik

### ISSUE THREAD

**Issue by mikebilly** [hansputera/tiktok-dl#90]
There used to be a "HD server" option to download source video, now it's not available anymore. Please bring it back (this issue appears across all tiktok downloader sites)

**Comment by hansputera** [comment]
Hello, can you please give me the video URL that is "HD Server"?

**Comment by mikebilly** [comment]
@hansputera Please test using the videos on my tiktok channel https://www.tiktok.com/@mikebilly79. The video downloaded should have the same fps and resolution written in the video title.

For example:
https://www.tiktok.com/@mikebilly79/video/7136035531347086593?is_copy_url=1&is_from_webapp=v1 is 4K60fps
![image](https://user-images.githubusercontent.com/29500216/187197199-fb0446c4-35dc-46e5-aa37-3a8081a59290.png)
This is what looks like on SnapTik. There used to be the "HD server" option between the "Download Server 01" and "Download Server 02" options. And, that video downloaded from SnapTik is 1024x576 60fps, but it should be 3840x2160 60fps. It should be like this: https://v16m-default.akamaized.net/a9a005ddd86a130a5392822326f17f0c/630cff31/video/tos/alisg/tos-alisg-pv-0037/cc4d70a5933246e894a54c314ff94715/?a=0&ch=0&cr=0&dr=0&cd=0%7C0%7C0%7C0&br=21784&bt=10892&ft=_rblsBnZqi2mo0PzwC7BkVQnNk6bHKJ&mime_type=video_mp4&qs=13&rc=M2pqazg6ZjY3ZjMzODgzNEBpM2pqazg6ZjY3ZjMzODgzNEBoLTRncjQwaDFgLS1kLy1zYSNoLTRncjQwaDFgLS1kLy1zcw%3D%3D&btag=40000&cc=3

**Comment by github-userx** [comment]
I do think TikTok removed/disabled the HD feature entirely (to save/limit bandwidth and storage on the entire platform). 

Looks like 4K/real HD videos are a thing of the past now.

Also @hansputera are you good with Python? yt-dlp has big issue with scraping entire userpages/feeds right now:  https://github.com/yt-dlp/yt-dlp/issues/3776
