### ISSUE TITLE
Deployment disabled

### ISSUE THREAD

**Issue by frozenpandaman** [hansputera/tiktok-dl#96]
Hi @hansputera, it seems the API is currently down:

https://tdl.besecure.eu.org/api/

402: PAYMENT_REQUIRED
Code: DEPLOYMENT_DISABLED

**Comment by hansputera** [comment]
Sorry for that, but my vercel account was blocked. And, you can see the image below
![Screenshot_2022-09-07-16-31-18-069_com google android gm](https://user-images.githubusercontent.com/47862061/188830512-2e80c391-a84b-42e5-8320-cec441f08d83.jpg)

Alternatively, you can deploy on your own vercel account 😅

**Comment by hansputera** [comment]
update (1 oct, 2022), you can access https://tdl.besecure.eu.org normally now

**Comment by frozenpandaman** [comment]
Thanks a ton @hansputera, yay! I have one remaining problem but will create a new issue for it now.
