### ISSUE TITLE
[BUG] - A bug

### ISSUE THREAD

**Issue by nurettinsansli** [hansputera/tiktok-dl#98]
FormInput.tsx?5751:33          POST http://localhost:3000/api/download 500 (Internal Server Error)

```
BBD
Scenario Outline: I should be able download video

Given I navigate to localhost:3000
When I paste "<url>" and click download button
Then I should be able to download video
Examples:
|                                             url                                                                  |
|https://www.tiktok.com/@merveeben/video/7089013920198823170?is_from_webapp=1&sender_device=pc&web_id=7150673846919513601|
```
![image](https://user-images.githubusercontent.com/45761126/193906448-e4c0509f-64d1-4fd0-918c-88d3046510f3.png)

![image](https://user-images.githubusercontent.com/45761126/193906571-440db1db-8836-48e5-8cc4-e529baa95b60.png)

**Comment by hansputera** [comment]
Can you send the nextjs server logs?
